global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "app_metrics"
    static_configs:
      - targets: ["app:8000"]
        labels:
          service: "sustainable_ai"

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          service: "node_exporter"

