global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sustainable_ai_app'
    static_configs:
      - targets: ['sustainable_ai_app:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['sustainable_ai_app:9100']

